import { type Product } from "../types/Product";

const products: Product[] = [
  {
    id: 1,
    name: "Wireless Headphones",
    description: "Experience high-fidelity sound with noise cancellation. Perfect for travel or remote work.",
    price: 129.99,
  },
  {
    id: 2,
    name: "Smartphone Stand",
    description: "A sleek aluminum stand for phones and small tablets. Keeps your desk tidy and ergonomic.",
    price: 15.99,
  },
  {
    id: 3,
    name: "Bluetooth Speaker",
    description: "Compact speaker with deep bass and waterproof design. Great for outdoor parties or the beach.",
    price: 49.99,
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    description: "Tactile keys with RGB lighting. Built for gamers and coders alike.",
    price: 89.99,
  },
  {
    id: 5,
    name: "LED Desk Lamp",
    description: "Dimmable LED lamp with touch controls and USB charging port. Sleek and efficient.",
    price: 32.5,
  },
  {
    id: 6,
    name: "USB-C Hub",
    description: "Expand your laptop’s connectivity with HDMI, USB 3.0, and SD card reader support.",
    price: 24.99,
  },
  {
    id: 7,
    name: "Noise Cancelling Earbuds",
    description: "In-ear design with active noise cancellation. Comes with a wireless charging case.",
    price: 79.95,
  },
  {
    id: 8,
    name: "Smart Thermostat",
    description: "Control your home temperature remotely. Learns your schedule for better efficiency.",
    price: 199.0,
  },
  {
    id: 9,
    name: "4K Monitor",
    description: "27-inch Ultra HD display with stunning color accuracy and thin bezels.",
    price: 329.99,
  },
  {
    id: 10,
    name: "Fitness Tracker",
    description: "Track steps, heart rate, and sleep patterns. Syncs with your smartphone.",
    price: 59.99,
  },
  {
    id: 11,
    name: "Portable SSD",
    description: "High-speed external storage with USB 3.2 support. Lightweight and shock-resistant.",
    price: 119.49,
  },
  {
    id: 12,
    name: "Ergonomic Chair",
    description: "Fully adjustable office chair with lumbar support. Great for long work hours.",
    price: 249.0,
  },
  {
    id: 13,
    name: "Standing Desk Converter",
    description: "Turns any desk into a sit-stand station. Gas-spring lift for easy adjustment.",
    price: 139.0,
  },
  {
    id: 14,
    name: "Smartwatch",
    description: "Stylish smartwatch with fitness tracking, notifications, and long battery life.",
    price: 179.99,
  },
  {
    id: 15,
    name: "Wireless Charger",
    description: "Fast charging pad compatible with all Qi-enabled devices. Sleek and minimalist.",
    price: 22.0,
  },
  {
    id: 16,
    name: "Gaming Mouse",
    description: "High-precision mouse with customizable buttons and RGB lighting.",
    price: 49.99,
  },
  {
    id: 17,
    name: "Laptop Stand",
    description: "Aluminum stand to elevate your laptop for better airflow and posture.",
    price: 29.99,
  },
  {
    id: 18,
    name: "Streaming Webcam",
    description: "Full HD 1080p webcam with built-in microphone. Ideal for Zoom or Twitch.",
    price: 69.99,
  },
  {
    id: 19,
    name: "Ring Light Kit",
    description: "Adjustable LED ring light with tripod for professional video lighting.",
    price: 45.0,
  },
  {
    id: 20,
    name: "Smart Light Bulbs (4-Pack)",
    description: "Color-changing bulbs controllable by app or voice. Works with Alexa and Google.",
    price: 39.95,
  },
  {
    id: 21,
    name: "Laptop Backpack",
    description: "Water-resistant backpack with padded laptop compartment and USB charging port.",
    price: 54.99,
  },
  {
    id: 22,
    name: "Tablet Sleeve",
    description: "Neoprene sleeve for tablets and small laptops. Lightweight and protective.",
    price: 13.49,
  },
  {
    id: 23,
    name: "Electric Kettle",
    description: "Rapid-boil kettle with temperature presets and auto shut-off. BPA-free.",
    price: 39.0,
  },
  {
    id: 24,
    name: "Smart Plug (2-Pack)",
    description: "Control appliances remotely with your phone. Voice-enabled for convenience.",
    price: 18.99,
  },
  {
    id: 25,
    name: "Wi-Fi Mesh Router",
    description: "High-speed mesh Wi-Fi system for whole-home coverage. Easy setup.",
    price: 199.99,
  },
  {
    id: 26,
    name: "External Monitor Arm",
    description: "Fully adjustable arm for single monitors. Clamp base fits any desk.",
    price: 58.95,
  },
  {
    id: 27,
    name: "Graphic Drawing Tablet",
    description: "Compact pen tablet for digital artists. Compatible with Windows and macOS.",
    price: 89.0,
  },
  {
    id: 28,
    name: "HDMI Capture Card",
    description: "Stream or record in 1080p from any HDMI device. Plug-and-play.",
    price: 79.99,
  },
  {
    id: 29,
    name: "Power Bank 20,000mAh",
    description: "Charge your phone multiple times on the go. Dual USB output and LED indicator.",
    price: 36.95,
  },
  {
    id: 30,
    name: "Phone Gimbal",
    description: "3-axis stabilizer for smooth smartphone video. Lightweight and foldable.",
    price: 99.99,
  },
  {
    id: 31,
    name: "Streaming Microphone",
    description: "USB condenser mic for podcasting or streaming. Cardioid pattern and pop filter.",
    price: 59.99,
  },
  {
    id: 32,
    name: "Electric Standing Desk",
    description: "Height-adjustable desk with memory presets and sturdy frame.",
    price: 329.0,
  },
  {
    id: 33,
    name: "Indoor Security Camera",
    description: "1080p video monitoring with night vision and motion alerts.",
    price: 44.0,
  },
  {
    id: 34,
    name: "Noise-Canceling Over-Ear Headphones",
    description: "Comfortable headphones with rich sound and long battery life.",
    price: 149.0,
  },
  {
    id: 35,
    name: "Bluetooth Tracker (4-Pack)",
    description: "Track your keys, wallet, and more. Works with iOS and Android.",
    price: 29.99,
  },
  {
    id: 36,
    name: "USB Microphone Arm Stand",
    description: "Adjustable arm for desk-mounted mics. Strong clamp and shock mount.",
    price: 24.95,
  },
  {
    id: 37,
    name: "Smart Home Hub",
    description: "Connect and control your smart devices from one central hub.",
    price: 89.99,
  },
  {
    id: 38,
    name: "Wireless Mouse",
    description: "Ergonomic mouse with silent clicks and long battery life.",
    price: 17.5,
  },
  {
    id: 39,
    name: "Dual Monitor Stand",
    description: "Mount two screens side-by-side with tilt and swivel features.",
    price: 75.0,
  },
  {
    id: 40,
    name: "USB Desk Fan",
    description: "Compact and quiet fan powered by USB. Perfect for desktops.",
    price: 14.99,
  },
  {
    id: 41,
    name: "Smart Alarm Clock",
    description: "Wake up with natural light simulation and customizable alarms.",
    price: 49.99,
  },
  {
    id: 42,
    name: "Keyboard & Mouse Combo",
    description: "Wireless combo with quiet keys and smooth tracking mouse.",
    price: 34.99,
  },
  {
    id: 43,
    name: "Laptop Cooling Pad",
    description: "Keeps your laptop cool with adjustable fan speeds and LED lights.",
    price: 28.49,
  },
  {
    id: 44,
    name: "Portable Projector",
    description: "Pocket-sized projector for movies or presentations. Supports HDMI and USB.",
    price: 189.0,
  },
  {
    id: 45,
    name: "Mini Desktop Vacuum",
    description: "Clean up crumbs and dust on your desk quickly and easily.",
    price: 12.95,
  },
  {
    id: 46,
    name: "USB LED Strip Lights",
    description: "Add RGB lighting to your desk setup. Remote-controlled brightness and color.",
    price: 19.99,
  },
  {
    id: 47,
    name: "Cable Management Box",
    description: "Hide messy power strips and cables in this sleek organizer box.",
    price: 21.99,
  },
  {
    id: 48,
    name: "Adjustable Phone Tripod",
    description: "Flexible legs and universal mount. Great for selfies or video recording.",
    price: 16.99,
  },
  {
    id: 49,
    name: "Clip-on Ring Light",
    description: "Attach to your laptop or phone for better lighting in video calls.",
    price: 14.99,
  },
  {
    id: 50,
    name: "Smart TV Remote",
    description: "Universal remote with voice control for most modern smart TVs.",
    price: 27.5,
  },
] as const;

export default products;
